name: Deploy to GH Pages
on:
  push:
    branches: [master]

jobs:
  build_and_deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Set up Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install python dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install JS dependencies
        run: npm install

      - name: Build
        run: lektor build -f scss -f npm

      - name: Deploy
        run: lektor deploy ghp_https --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
